spring:
  application:
    name: order
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://192.168.0.14:3306/springcloud_sell?characterEncoding=utf-8&useSSL=false
  rabbitmq:
    host: 192.168.0.14
    port: 5672
    username: guest
    password: guest
#eureka:
#  client:
#    service-url:
#      defaultZone: http://192.168.0.12:8761/eureka/
#  instance:
#    prefer-ip-address: true
#自定义某个应用名，使用自定义负载均衡规则
#PRODUCT:
#  ribbon:
#    NFLoadBalancerRuleClassName:  com.netflix.loadbalancer.RandomRule
