spring:
  application:
    name: product
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://192.168.0.12:3306/springcloud_sell?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true